In [55]:
import pandas as pd
import os
import numpy as np
from datetime import timedelta

In [56]:
attendance_df= pd.read_csv('attendance.csv')
train_df = pd.read_csv('train.csv')
submission = pd.read_csv('submission.csv')

In [57]:
attendance_df

                                    user_id                    datetime
0      5931fa6a-af6b-43b8-babb-28349854d406  2024-04-19 17:30:08.827555
1      5f1a2ecf-943d-446b-b94d-d7d1ad64213d  2024-04-19 17:30:11.405020
2      6e009a96-2b8b-4048-8b0c-20a7924a4b4f  2024-04-19 17:30:14.433098
3      cdd098ee-4295-4839-b1a3-4d44840feacd  2024-04-19 17:30:17.214453
4      f922a5d4-3651-46f7-aa98-307c045dd4b5  2024-04-19 17:30:21.556805
...                                     ...                         ...
10798  ef836255-9ff1-48bd-9ee1-b3e205f96367  2024-05-17 13:57:11.458189
10799  84aea5bb-fc9f-463e-8ed9-5c36ccb0dc7f  2024-05-17 13:57:15.457449
10800  1e103917-1d29-424d-b5e1-924e0cdcd6dc  2024-05-17 13:57:19.924906
10801  9207b26d-79dc-41fc-b62c-67a6821132b9  2024-05-17 14:01:03.323543
10802  25e69851-885b-4cd1-8c32-e29e604714ea  2024-05-17 14:01:05.950781

[10803 rows x 2 columns]

In [58]:
attendance_df['datetime'] = attendance_df['datetime'].sort_values()

In [59]:
attendance_df

                                    user_id                    datetime
0      5931fa6a-af6b-43b8-babb-28349854d406  2024-04-19 17:30:08.827555
1      5f1a2ecf-943d-446b-b94d-d7d1ad64213d  2024-04-19 17:30:11.405020
2      6e009a96-2b8b-4048-8b0c-20a7924a4b4f  2024-04-19 17:30:14.433098
3      cdd098ee-4295-4839-b1a3-4d44840feacd  2024-04-19 17:30:17.214453
4      f922a5d4-3651-46f7-aa98-307c045dd4b5  2024-04-19 17:30:21.556805
...                                     ...                         ...
10798  ef836255-9ff1-48bd-9ee1-b3e205f96367  2024-05-17 13:57:11.458189
10799  84aea5bb-fc9f-463e-8ed9-5c36ccb0dc7f  2024-05-17 13:57:15.457449
10800  1e103917-1d29-424d-b5e1-924e0cdcd6dc  2024-05-17 13:57:19.924906
10801  9207b26d-79dc-41fc-b62c-67a6821132b9  2024-05-17 14:01:03.323543
10802  25e69851-885b-4cd1-8c32-e29e604714ea  2024-05-17 14:01:05.950781

[10803 rows x 2 columns]

In [60]:
attendance_df = attendance_df.merge(train_df, on='user_id', how='left')

In [61]:
attendance_df

,user_id,datetime,house
0,5931fa6a-af6b-43b8-babb-28349854d406,2024-04-19 17:30:08.827555,NaN
1,5f1a2ecf-943d-446b-b94d-d7d1ad64213d,2024-04-19 17:30:11.405020,NaN
2,6e009a96-2b8b-4048-8b0c-20a7924a4b4f,2024-04-19 17:30:14.433098,NaN
3,cdd098ee-4295-4839-b1a3-4d44840feacd,2024-04-19 17:30:17.214453,house3
4,f922a5d4-3651-46f7-aa98-307c045dd4b5,2024-04-19 17:30:21.556805,NaN
...,...,...,...
10798,ef836255-9ff1-48bd-9ee1-b3e205f96367,2024-05-17 13:57:11.458189,NaN
10799,84aea5bb-fc9f-463e-8ed9-5c36ccb0dc7f,2024-05-17 13:57:15.457449,house3
10800,1e103917-1d29-424d-b5e1-924e0cdcd6dc,2024-05-17 13:57:19.924906,NaN
10801,9207b26d-79dc-41fc-b62c-67a6821132b9,2024-05-17 14:01:03.323543,house3
10802,25e69851-885b-4cd1-8c32-e29e604714ea,2024-05-17 14:01:05.950781,house3

In [62]:
attendance_df['house'].isnull().sum()

4319

In [63]:
attendance_df['house'] = attendance_df['house'].ffill()

In [64]:
attendance_df = attendance_df.sort_values('datetime')
attendance_df

,user_id,datetime,house
1304,517fac56-4785-40b1-a43e-561275caae77,2024-04-18 23:09:34.716699,house3
1305,e5763aad-656b-44d6-ad74-93a40495a5b3,2024-04-18 23:09:37.495417,house2
1306,12e832b1-ba8d-48d4-acb1-67c2ed2504e4,2024-04-18 23:09:38.633737,house2
1307,1fcf9cd7-6858-400d-b8c4-446dd76036e4,2024-04-18 23:09:39.745934,house2
1308,8c7a8814-d01f-40fa-817a-32358419b0a1,2024-04-18 23:09:40.640142,house2
...,...,...,...
10798,ef836255-9ff1-48bd-9ee1-b3e205f96367,2024-05-17 13:57:11.458189,house4
10799,84aea5bb-fc9f-463e-8ed9-5c36ccb0dc7f,2024-05-17 13:57:15.457449,house3
10800,1e103917-1d29-424d-b5e1-924e0cdcd6dc,2024-05-17 13:57:19.924906,house3
10801,9207b26d-79dc-41fc-b62c-67a6821132b9,2024-05-17 14:01:03.323543,house3
10802,25e69851-885b-4cd1-8c32-e29e604714ea,2024-05-17 14:01:05.950781,house3

In [65]:
attendance_df = attendance_df.groupby('user_id')['house'].agg(lambda x: x.mode()[0] if not x.mode().empty else None)

In [66]:
attendance_df

user_id
0492584f-5dda-4ad6-ab2f-79c8d43a8753    house1
0a3e80d5-ebfc-4fb6-9c73-eb4afcca687a    house3
0cb94071-a8ec-4885-8316-e0e4fbebec32    house3
0d9ff778-c1fe-4966-baa9-e35783893f39    house2
0e59353d-8c6d-4a18-876e-5f506a40036e    house5
                                         ...
f90e665a-2d98-4ab1-a6de-5ce1a5403861    house2
f922a5d4-3651-46f7-aa98-307c045dd4b5    house5
faac7a28-16cd-48ae-833d-09ea4ae49833    house3
fac56dec-f876-400b-921f-94012ed87d73    house6
fed3dced-4009-461e-9411-a440c779e32c    house5
Name: house, Length: 170, dtype: object

In [67]:
# attendance_df = attendance_df.reset_index().drop_duplicates(subset='user_id', keep='first').set_index('index')

In [75]:
attendance_df.to_csv('test.csv')

In [77]:
attendance_df = pd.read_csv('test.csv')
attendance_df

                                  user_id   house
0    0492584f-5dda-4ad6-ab2f-79c8d43a8753  house1
1    0a3e80d5-ebfc-4fb6-9c73-eb4afcca687a  house3
2    0cb94071-a8ec-4885-8316-e0e4fbebec32  house3
3    0d9ff778-c1fe-4966-baa9-e35783893f39  house2
4    0e59353d-8c6d-4a18-876e-5f506a40036e  house5
..                                    ...     ...
165  f90e665a-2d98-4ab1-a6de-5ce1a5403861  house2
166  f922a5d4-3651-46f7-aa98-307c045dd4b5  house5
167  faac7a28-16cd-48ae-833d-09ea4ae49833  house3
168  fac56dec-f876-400b-921f-94012ed87d73  house6
169  fed3dced-4009-461e-9411-a440c779e32c  house5

[170 rows x 2 columns]

In [78]:
attendance_df = attendance_df.sort_values('user_id').reset_index(drop=True)
attendance_df

                                  user_id   house
0    0492584f-5dda-4ad6-ab2f-79c8d43a8753  house1
1    0a3e80d5-ebfc-4fb6-9c73-eb4afcca687a  house3
2    0cb94071-a8ec-4885-8316-e0e4fbebec32  house3
3    0d9ff778-c1fe-4966-baa9-e35783893f39  house2
4    0e59353d-8c6d-4a18-876e-5f506a40036e  house5
..                                    ...     ...
165  f90e665a-2d98-4ab1-a6de-5ce1a5403861  house2
166  f922a5d4-3651-46f7-aa98-307c045dd4b5  house5
167  faac7a28-16cd-48ae-833d-09ea4ae49833  house3
168  fac56dec-f876-400b-921f-94012ed87d73  house6
169  fed3dced-4009-461e-9411-a440c779e32c  house5

[170 rows x 2 columns]

In [79]:
submission = submission.sort_values('user_id').reset_index(drop=True)
submission

                                 user_id house
0   0cb94071-a8ec-4885-8316-e0e4fbebec32   NaN
1   0d9ff778-c1fe-4966-baa9-e35783893f39   NaN
2   12584309-4699-485d-9f5b-a57ebfc4283a   NaN
3   1a024edc-e397-4508-958e-7051ae278650   NaN
4   1bedb648-5a50-4680-a09b-27240759f9a0   NaN
..                                   ...   ...
63  e81fe35d-eabc-4bef-a19d-b7cf24d01366   NaN
64  ef836255-9ff1-48bd-9ee1-b3e205f96367   NaN
65  f89e8057-94eb-42d4-9ea6-c5f00419c387   NaN
66  f922a5d4-3651-46f7-aa98-307c045dd4b5   NaN
67  fed3dced-4009-461e-9411-a440c779e32c   NaN

[68 rows x 2 columns]

In [80]:
id = []
p = []

for i in range(len(attendance_df)):
  for j in range(len(submission)):
    if attendance_df['user_id'][i] == submission['user_id'][j]:
      id.append(attendance_df['user_id'][i])
      p.append(attendance_df['house'][i])
      print(attendance_df['user_id'][i] , attendance_df['house'][i],submission['user_id'][j])
      break

0cb94071-a8ec-4885-8316-e0e4fbebec32 house3 0cb94071-a8ec-4885-8316-e0e4fbebec32
0d9ff778-c1fe-4966-baa9-e35783893f39 house2 0d9ff778-c1fe-4966-baa9-e35783893f39
12584309-4699-485d-9f5b-a57ebfc4283a house5 12584309-4699-485d-9f5b-a57ebfc4283a
1a024edc-e397-4508-958e-7051ae278650 house4 1a024edc-e397-4508-958e-7051ae278650
1bedb648-5a50-4680-a09b-27240759f9a0 house3 1bedb648-5a50-4680-a09b-27240759f9a0
1d4297fd-0875-41c6-bbdd-6c7d22c2411f house5 1d4297fd-0875-41c6-bbdd-6c7d22c2411f
1e103917-1d29-424d-b5e1-924e0cdcd6dc house3 1e103917-1d29-424d-b5e1-924e0cdcd6dc
2e333d17-d22d-42c6-b7e2-57bd681b1415 house6 2e333d17-d22d-42c6-b7e2-57bd681b1415
2e958eb1-0ca7-444a-a150-6e1f2e74735b house4 2e958eb1-0ca7-444a-a150-6e1f2e74735b
301ea4b1-4d7d-4164-81d4-9d12fb0c16f3 house3 301ea4b1-4d7d-4164-81d4-9d12fb0c16f3
31f1dfb3-1ed4-4fed-9ef0-952b9a70b3f6 house4 31f1dfb3-1ed4-4fed-9ef0-952b9a70b3f6
3224a678-3fef-47ae-94e5-3250cec710f9 house2 3224a678-3fef-47ae-94e5-3250cec710f9
337efdeb-7299-4e86-9db0-3b7bad905ca4 house2 337efdeb-7299-4e86-9db0-3b7bad905ca4
3a90e6b3-bc9f-49a7-997f-e954943de83e house1 3a90e6b3-bc9f-49a7-997f-e954943de83e
422a524d-cfb0-4b28-b521-d32f9447263e house6 422a524d-cfb0-4b28-b521-d32f9447263e
4341cf2a-0952-459b-b895-9e25b8e230fe house5 4341cf2a-0952-459b-b895-9e25b8e230fe
4503e76c-39a4-41e8-bbd4-0b91a9240aaa house2 4503e76c-39a4-41e8-bbd4-0b91a9240aaa
477b6e5c-ed43-44dd-8391-e790f22f240d house5 477b6e5c-ed43-44dd-8391-e790f22f240d
48ed7588-0b5b-40c9-9fc3-9d5c51a0c88a house5 48ed7588-0b5b-40c9-9fc3-9d5c51a0c88a
4af43656-b123-4a72-892b-7993a6355ed3 house4 4af43656-b123-4a72-892b-7993a6355ed3
517fac56-4785-40b1-a43e-561275caae77 house2 517fac56-4785-40b1-a43e-561275caae77
5931fa6a-af6b-43b8-babb-28349854d406 house5 5931fa6a-af6b-43b8-babb-28349854d406
5b4b687b-64db-4ee8-9fd6-42931ca7576c house2 5b4b687b-64db-4ee8-9fd6-42931ca7576c
5cd9c8db-07cf-4b5f-a590-00af8dacc4a4 house3 5cd9c8db-07cf-4b5f-a590-00af8dacc4a4
5f1a2ecf-943d-446b-b94d-d7d1ad64213d house3 5f1a2ecf-943d-446b-b94d-d7d1ad64213d
5f47549a-4365-484f-9f7f-5a471b91c981 house6 5f47549a-4365-484f-9f7f-5a471b91c981
60fea3c0-9066-49ea-beb2-b055ab2b4ff9 house1 60fea3c0-9066-49ea-beb2-b055ab2b4ff9
61ed2314-8e12-4316-8099-8d99363ac48e house5 61ed2314-8e12-4316-8099-8d99363ac48e
636b1c8b-4934-4842-9642-5283b06d7e9f house2 636b1c8b-4934-4842-9642-5283b06d7e9f
63a28e63-51c2-46bb-baa3-87693efd4424 house1 63a28e63-51c2-46bb-baa3-87693efd4424
64d93c1a-1a53-4f12-8590-58cb738cd3b1 house6 64d93c1a-1a53-4f12-8590-58cb738cd3b1
67054eb5-41f1-4d11-aed8-465e8a5bafab house1 67054eb5-41f1-4d11-aed8-465e8a5bafab
6e009a96-2b8b-4048-8b0c-20a7924a4b4f house3 6e009a96-2b8b-4048-8b0c-20a7924a4b4f
6e9afd62-0755-4cf4-a956-c5d3e22b6038 house4 6e9afd62-0755-4cf4-a956-c5d3e22b6038
71d0528a-188d-4aba-b7de-79ce11aba729 house6 71d0528a-188d-4aba-b7de-79ce11aba729
72f607f4-67b9-459a-9712-76fa6ca47874 house6 72f607f4-67b9-459a-9712-76fa6ca47874
7474c4b5-d72d-4213-ad48-c8376a66cf35 house6 7474c4b5-d72d-4213-ad48-c8376a66cf35
818aab23-2383-4450-911e-88d07af57dd0 house3 818aab23-2383-4450-911e-88d07af57dd0
81c9f456-b5a2-4e28-ad69-eb7d89374d37 house1 81c9f456-b5a2-4e28-ad69-eb7d89374d37
87176cb2-0b72-4207-9738-d14f9e7b35fc house2 87176cb2-0b72-4207-9738-d14f9e7b35fc
897eb4f1-64df-488f-824c-68b83e97d48a house2 897eb4f1-64df-488f-824c-68b83e97d48a
8ce55900-508f-44eb-b01a-e217d46bfd5a house5 8ce55900-508f-44eb-b01a-e217d46bfd5a
90be5909-0039-4170-a115-3dba964d3c70 house1 90be5909-0039-4170-a115-3dba964d3c70
99352c97-a615-425e-8c20-6838d99297da house1 99352c97-a615-425e-8c20-6838d99297da
9af32f95-5e33-4ee7-8f46-e5399bc10479 house4 9af32f95-5e33-4ee7-8f46-e5399bc10479
a5e1de79-b29f-4942-b74d-3cf6bf77682f house6 a5e1de79-b29f-4942-b74d-3cf6bf77682f
aad41422-3ccd-4920-a077-ea696e7cd61f house6 aad41422-3ccd-4920-a077-ea696e7cd61f
b10aa190-3d2a-4137-b674-8cb64824d72c house2 b10aa190-3d2a-4137-b674-8cb64824d72c
b349e5e0-8128-432e-a8a4-03b754f07f36 house2 b349e5e0-8128-432e-a8a4-03b754f07f36
b455da87-de96-42b3-b126-1f350de41e8c house1 b455da87-de96-42b3-b126-1f350de41e8c
c09f4e21-93f1-4ee5-8be8-5892f9e3f67b house1 c09f4e21-93f1-4ee5-8be8-5892f9e3f67b
c3728021-30dd-44a0-9585-edfa84506a97 house4 c3728021-30dd-44a0-9585-edfa84506a97
c40c417e-6ec1-4634-9f5a-e8daa1ad8a16 house4 c40c417e-6ec1-4634-9f5a-e8daa1ad8a16
c813c2bc-7886-4013-a340-6b71b8d13003 house3 c813c2bc-7886-4013-a340-6b71b8d13003
c968fef9-5411-49d5-b6e1-d9a52add4ab8 house6 c968fef9-5411-49d5-b6e1-d9a52add4ab8
ce9c3ed2-1b0f-415d-9502-504ae224491a house6 ce9c3ed2-1b0f-415d-9502-504ae224491a
cf51b9c2-7ff5-40f3-a752-0a9480fdd894 house4 cf51b9c2-7ff5-40f3-a752-0a9480fdd894
d6a7c304-337f-41ab-8d21-318c2955ba0b house4 d6a7c304-337f-41ab-8d21-318c2955ba0b
da987f6e-e9ee-4c8a-aa1f-d801d4c35644 house5 da987f6e-e9ee-4c8a-aa1f-d801d4c35644
dc9690fd-c8d0-46a3-844d-28842ee4af4f house1 dc9690fd-c8d0-46a3-844d-28842ee4af4f
dda733a2-2add-44a5-b888-81943923c2c6 house4 dda733a2-2add-44a5-b888-81943923c2c6
e3aca4f2-7e1e-4499-bf8f-55355b2849da house1 e3aca4f2-7e1e-4499-bf8f-55355b2849da
e69e0495-522a-4fcb-9da1-644601d99e2b house1 e69e0495-522a-4fcb-9da1-644601d99e2b
e81fe35d-eabc-4bef-a19d-b7cf24d01366 house2 e81fe35d-eabc-4bef-a19d-b7cf24d01366
ef836255-9ff1-48bd-9ee1-b3e205f96367 house3 ef836255-9ff1-48bd-9ee1-b3e205f96367
f89e8057-94eb-42d4-9ea6-c5f00419c387 house5 f89e8057-94eb-42d4-9ea6-c5f00419c387
f922a5d4-3651-46f7-aa98-307c045dd4b5 house5 f922a5d4-3651-46f7-aa98-307c045dd4b5
fed3dced-4009-461e-9411-a440c779e32c house5 fed3dced-4009-461e-9411-a440c779e32c

In [81]:
sub = pd.DataFrame({
    'user_id' : id,
    'house' : p
})

In [82]:
sub

                                 user_id   house
0   0cb94071-a8ec-4885-8316-e0e4fbebec32  house3
1   0d9ff778-c1fe-4966-baa9-e35783893f39  house2
2   12584309-4699-485d-9f5b-a57ebfc4283a  house5
3   1a024edc-e397-4508-958e-7051ae278650  house4
4   1bedb648-5a50-4680-a09b-27240759f9a0  house3
..                                   ...     ...
63  e81fe35d-eabc-4bef-a19d-b7cf24d01366  house2
64  ef836255-9ff1-48bd-9ee1-b3e205f96367  house3
65  f89e8057-94eb-42d4-9ea6-c5f00419c387  house5
66  f922a5d4-3651-46f7-aa98-307c045dd4b5  house5
67  fed3dced-4009-461e-9411-a440c779e32c  house5

[68 rows x 2 columns]

In [83]:
sub['user_id'].isnull().sum()

0

In [84]:
sub.to_csv('sub_Hat_5.csv',index = False)

In [87]:
sub['house'].value_counts()

house
house2    12
house5    12
house1    12
house4    11
house6    11
house3    10
Name: count, dtype: int64